name: alpha_flutter_project
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  #sdk: ^3.7.0-312.0.dev
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  stream_transform: ^2.1.1
  bloc_concurrency: ^0.3.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  file_uploader_repository:
    path: packages/file_uploader_repository
  social_media_list_form_repository:
    path: packages/social_media_list_form_repository
  image_viewer:
    path: packages/image_viewer
  formz: ^0.8.0
  hydrated_bloc: ^10.0.0
  json_annotation: ^4.8.1
  path_provider: ^2.0.8
  weather_repository:
    path: packages/weather_repository
  google_fonts: ^6.2.1
  flutter_admin_scaffold: ^1.4.0
  dotted_border: ^2.1.0
  permission_handler: ^11.4.0
  calendar_date_picker2: ^1.1.9
  flutter_localization: ^0.3.1
  http: ^1.0.0
  font_awesome_flutter: ^10.8.0
  event_bus: ^2.0.1
  localization_service:
    path: packages/localization_service
  alert_banner: ^1.0.1
  percent_indicator: ^4.2.4
  video_viewer:
    path: packages/video_viewer
  rive_animated_icon: ^2.0.3
  blinking_text: ^1.0.4
  social_media_publications_repository:
    path: packages/social_media_publications_repository
  loading_animation_widget: ^1.3.0
  qrcode_list_repository:
    path: packages/qrcode_list_repository
  calendar_view: ^1.4.0
  flutter_date_range_picker: ^0.1.1
dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^1.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/common/
    - assets/images/social_media_publications_list/
    - assets/localization/
    - lib/i18n_testing/src/lang/
    - lib/social_media_file_uploader_form/lang/
    - lib/social_media_publications_list/src/lang/
    - lib/social_media_list_form/src/lang/