name: alpha_flutter_project
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0-312.0.dev


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  http: ^1.3.0
  stream_transform: ^2.1.1
  bloc_concurrency: ^0.3.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository  
  formz: ^0.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
