//external library
export 'package:formz/formz.dart';
export 'package:equatable/equatable.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
//view packages
export "package:flutter/material.dart";
//internal packages
export 'package:authentication_repository/authentication_repository.dart';
//module exports
export "data/data.dart";
export "presentation/presentation.dart";
export "domain/domain.dart";
